# .github/dependabot.yml
version: 2

updates:
  # scrute mes GitHub Actions pour les mettre à jour chaque mois
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Pour mes plugins Python, je fais tourner Dependabot chaque semaine
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dockerfile toutes mes dépendances système, actualise aussi chaque semaine
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"